export const INFO_LOAD = 'INFO_LOAD';
export const INFO_LOAD_SUCCESS = 'INFO_LOAD_SUCCESS';
export const INFO_LOAD_FAIL = 'INFO_LOAD_FAIL';
export const WIDGET_LOAD = 'WIDGET_LOAD';
export const WIDGET_LOAD_SUCCESS = 'WIDGET_LOAD_SUCCESS';
export const WIDGET_LOAD_FAIL = 'WIDGET_LOAD_FAIL';
export const AUTH_LOAD = 'AUTH_LOAD';
export const AUTH_LOAD_SUCCESS = 'AUTH_LOAD_SUCCESS';
export const AUTH_LOAD_FAIL = 'AUTH_LOAD_FAIL';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAIL = 'AUTH_LOGOUT_FAIL';
export const COUNTER_INCREMENT = 'COUNTER_INCREMENT';

export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const FETCH_MOODS = 'FETCH_MOODS';
export const FETCH_MOODS_SUCCESS = 'FETCH_MOODS_SUCCESS';
export const FETCH_MOODS_FAIL = 'FETCH_MOODS_FAIL';

export const ADD_MOOD = 'ADD_MOOD';
export const ADD_MOOD_SUCCESS = 'ADD_MOOD_SUCCESS';
export const ADD_MOOD_FAIL = 'ADD_MOOD_FAIL';

export const FBAUTH = 'FBAUTH';
export const FBAUTH_SUCCESS = 'FBAUTH_SUCCESS';
export const FBAUTH_FAIL = 'FBAUTH_FAIL';
